-- Contract sending and verified client access (read-only; no signing yet).
--
-- Flow and responsibilities:
--   1. Staff send (send_contract): one transaction locks event, proposal and
--      contract, re-runs private.contract_send_problems, marks the contract
--      sent (sent_at stamped once by the database), creates an expiring
--      contract invitation in access_links (purpose 'contract', scoped to the
--      tenant, event, contract and frozen signer), queues the contract email
--      and writes an audit record. Repeats return the existing result.
--   2. The invitation token is derived on the server as
--      HMAC(PROPOSAL_LINK_SECRET, "flux:contract-invite:v1:" + link id); only
--      sha256(token) is stored. It authorizes exactly one thing: asking for a
--      verification email to the frozen signer address
--      (request_contract_sign_in). It is never proof of identity.
--   3. The verification email's Supabase link is generated by the outbox
--      worker at delivery time (Auth admin API) and never stored.
--   4. After the client verifies their email through Supabase Auth and
--      confirms, accept_contract_invitation grants event access, idempotently,
--      to the exact tenant, event and signer client, and only if the verified
--      email matches the frozen signer email.
--   5. client_contract_view returns a safe DTO of the frozen contract after
--      rechecking identity, access, signer and eligibility on every read.
--
-- Resend replaces the invitation (old one revoked, pending emails cancelled);
-- void ends an unsigned sent contract. Signing is not implemented: no status
-- can reach 'signed'.

-- ===========================================================================
-- Tenant slugs: "my" is the client home route
-- ===========================================================================

create or replace function private.is_valid_tenant_slug(slug text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select slug ~ '^[a-z0-9][a-z0-9-]{1,46}[a-z0-9]$'
     and slug !~ '--'
     and slug not in (
       'admin', 'api', 'app', 'assets', 'auth', 'callback', 'dashboard', 'flux',
       'fluxdj', 'help', 'legal', 'login', 'logout', 'manifest', 'my', 'offline',
       'privacy', 'public', 'settings', 'signin', 'signup', 'staff', 'static',
       'support', 'terms', 'www'
     );
$$;

-- ===========================================================================
-- Contracts: sent and void states
-- ===========================================================================

alter table public.contracts
  add column sent_at timestamptz,
  add column voided_at timestamptz,
  add column void_reason text
    constraint contracts_void_reason_length check (length(btrim(void_reason)) between 1 and 500),
  add constraint contracts_sent_at_matches_status check ((status in ('sent', 'signed', 'void')) = (sent_at is not null)),
  add constraint contracts_void_matches_status check ((status = 'void') = (voided_at is not null and void_reason is not null));
comment on column public.contracts.sent_at is 'When the contract was first sent. Set once by the database; resends never change it.';

-- Permitted transitions in this stage: draft -> replaced | superseded | sent,
-- and sent -> void. Signing arrives later. The database stamps the times.
create or replace function private.contracts_status_transition()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status is distinct from old.status then
    if not ((old.status = 'draft' and new.status in ('replaced', 'superseded', 'sent'))
         or (old.status = 'sent' and new.status = 'void')) then
      raise exception 'contract cannot move from % to %', old.status, new.status using errcode = 'check_violation';
    end if;
    -- Only send_contract may send: it sets this transaction-local marker after
    -- its eligibility checks, together with the invitation, email and audit.
    if new.status = 'sent' and current_setting('flux.sending_contract', true) is distinct from new.id::text then
      raise exception 'contracts are sent only through send_contract' using errcode = 'check_violation';
    end if;
    new.status_changed_at := now();
    if new.status = 'sent' then new.sent_at := now(); end if;
    if new.status = 'void' then new.voided_at := now(); end if;
  elsif new.status_changed_at is distinct from old.status_changed_at then
    raise exception 'contracts.status_changed_at is set by the database' using errcode = 'check_violation';
  end if;
  if old.sent_at is not null and new.sent_at is distinct from old.sent_at then
    raise exception 'contracts.sent_at cannot change once set' using errcode = 'check_violation';
  end if;
  if old.status = 'void' and (new.voided_at is distinct from old.voided_at or new.void_reason is distinct from old.void_reason) then
    raise exception 'a void contract cannot change' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

-- ===========================================================================
-- Contract invitations (access_links, purpose 'contract')
-- ===========================================================================

alter table public.access_links drop constraint access_links_purpose_valid;
alter table public.access_links
  add column contract_id uuid,
  add constraint access_links_purpose_valid check (purpose in ('proposal', 'contract')),
  add constraint access_links_contract_scope check ((purpose = 'contract') = (contract_id is not null)),
  add constraint access_links_contract_fk foreign key (tenant_id, contract_id)
    references public.contracts (tenant_id, id) on delete restrict;
comment on column public.access_links.contract_id is 'For contract invitations: the contract. The invitation never proves identity; it only lets the frozen signer request a verification email.';
create unique index access_links_one_active_contract_link_idx
  on public.access_links (contract_id) where purpose = 'contract' and revoked_at is null;
create index access_links_tenant_contract_idx on public.access_links (tenant_id, contract_id);

drop trigger access_links_immutable on public.access_links;
create trigger access_links_immutable before update on public.access_links
  for each row execute function private.forbid_column_changes(
    'id', 'tenant_id', 'purpose', 'proposal_id', 'contract_id', 'intended_client_id', 'token_hash', 'expires_at', 'created_at');

-- A contract invitation must match its contract's proposal and frozen signer.
create function private.access_links_contract_scope()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.purpose = 'contract' and not exists (
    select 1 from public.contracts c
    where c.tenant_id = new.tenant_id and c.id = new.contract_id
      and c.proposal_id = new.proposal_id and c.signer_client_id = new.intended_client_id
  ) then
    raise exception 'a contract invitation must match its contract''s proposal and signer' using errcode = 'check_violation';
  end if;
  return new;
end;
$$;
revoke execute on function private.access_links_contract_scope() from public, anon, authenticated;
create trigger access_links_contract_scope before insert on public.access_links
  for each row execute function private.access_links_contract_scope();

grant select (contract_id) on public.access_links to authenticated;

-- ===========================================================================
-- Email outbox: contract emails
-- ===========================================================================

alter table public.email_outbox drop constraint email_outbox_event_type_valid;
alter table public.email_outbox drop constraint email_outbox_entity_type_valid;
alter table public.email_outbox
  add constraint email_outbox_event_type_valid check (event_type in (
    'proposal_sent', 'proposal_link_opened', 'proposal_submitted', 'proposal_approved',
    'contract_sent', 'contract_sign_in')),
  add constraint email_outbox_entity_type_valid check (entity_type in ('proposal', 'contract'));
create index email_outbox_tenant_entity_idx on public.email_outbox (tenant_id, entity_type, entity_id, status);

create function private.enqueue_contract_email(
  p_tenant_id uuid, p_event_type text, p_recipient text, p_contract_id uuid, p_link_id uuid, p_payload jsonb, p_dedup_key text
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.email_outbox (tenant_id, event_type, recipient_email, entity_type, entity_id, access_link_id, payload, dedup_key)
  values (p_tenant_id, p_event_type, lower(p_recipient), 'contract', p_contract_id, p_link_id, coalesce(p_payload, '{}'::jsonb), p_dedup_key)
  on conflict (dedup_key) do nothing;
$$;
revoke execute on function private.enqueue_contract_email(uuid, text, text, uuid, uuid, jsonb, text) from public, anon, authenticated;

-- Revokes a contract's invitations and cancels its pending emails.
create function private.retire_contract_invitations(p_contract_id uuid, p_reason text)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.access_links set revoked_at = now()
    where purpose = 'contract' and contract_id = p_contract_id and revoked_at is null;
  update public.email_outbox set status = 'cancelled', last_error = left(p_reason, 1000)
    where entity_type = 'contract' and entity_id = p_contract_id and status = 'pending';
$$;
revoke execute on function private.retire_contract_invitations(uuid, text) from public, anon, authenticated;

drop function public.claim_email_outbox(integer, integer, uuid);
create function public.claim_email_outbox(p_limit integer default 10, p_lock_seconds integer default 120, p_tenant_id uuid default null)
returns table (
  id uuid, tenant_id uuid, event_type text, recipient_email text, entity_id uuid, payload jsonb, attempts integer,
  access_link_id uuid, link_token_hash text, link_usable boolean, proposal_active boolean,
  tenant_slug text, tenant_display_name text, tenant_reply_to text,
  contract_deliverable boolean, contract_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
#variable_conflict use_column
begin
  -- Claims that expired with no attempts left are given up.
  update public.email_outbox o
    set status = 'failed', locked_until = null, last_error = coalesce(o.last_error, 'delivery did not complete')
    where o.status = 'sending' and o.locked_until < now() and o.attempts >= o.max_attempts
      and (p_tenant_id is null or o.tenant_id = p_tenant_id);

  return query
  with due as (
    select o.id from public.email_outbox o
    where (o.status = 'pending' or (o.status = 'sending' and o.locked_until < now()))
      and o.next_attempt_at <= now()
      and o.attempts < o.max_attempts
      and (p_tenant_id is null or o.tenant_id = p_tenant_id)
      -- Archived businesses send nothing.
      and exists (select 1 from public.tenants t where t.id = o.tenant_id and t.archived_at is null)
    order by o.next_attempt_at
    limit greatest(1, least(coalesce(p_limit, 10), 100))
    for update skip locked
  ),
  claimed as (
    update public.email_outbox o
      set status = 'sending', attempts = o.attempts + 1,
          locked_until = now() + make_interval(secs => greatest(10, least(coalesce(p_lock_seconds, 120), 900)))
      from due where o.id = due.id
      returning o.*
  )
  select c.id, c.tenant_id, c.event_type, c.recipient_email, c.entity_id, c.payload, c.attempts,
         c.access_link_id, l.token_hash, (l.id is not null and l.revoked_at is null and l.expires_at > now()),
         coalesce(e.active_proposal_id = c.entity_id, false),
         t.slug, t.display_name, t.reply_to_email,
         -- Contract emails are deliverable only while their invitation is
         -- usable and the contract is still sent, current and not archived.
         coalesce(c.entity_type = 'contract' and l.purpose = 'contract' and l.contract_id = c.entity_id
                  and l.revoked_at is null and l.expires_at > now()
                  and k.status = 'sent' and ke.archived_at is null
                  and kp.status = 'approved' and ke.active_proposal_id = k.proposal_id, false),
         k.id
  from claimed c
  join public.tenants t on t.id = c.tenant_id
  left join public.access_links l on l.tenant_id = c.tenant_id and l.id = c.access_link_id
  left join public.proposals p on p.tenant_id = c.tenant_id and p.id = c.entity_id
  left join public.events e on e.tenant_id = p.tenant_id and e.id = p.event_id
  left join public.contracts k on c.entity_type = 'contract' and k.tenant_id = c.tenant_id and k.id = c.entity_id
  left join public.events ke on ke.tenant_id = k.tenant_id and ke.id = k.event_id
  left join public.proposals kp on kp.tenant_id = k.tenant_id and kp.id = k.proposal_id;
end;
$$;

revoke execute on function public.claim_email_outbox(integer, integer, uuid) from public, anon, authenticated;
grant execute on function public.claim_email_outbox(integer, integer, uuid) to service_role;

-- ===========================================================================
-- Eligibility (sent contracts may be resent), generation and archiving
-- ===========================================================================

create or replace function private.contract_send_problems(p_contract_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
  e public.events%rowtype;
  p public.proposals%rowtype;
  t public.tenants%rowtype;
  v_signer record;
  v_frozen jsonb;
  v_problems jsonb := '[]'::jsonb;
  v_identity_changes text[] := '{}'::text[];
begin
  select * into c from public.contracts where id = p_contract_id;
  if not found then
    return jsonb_build_array(jsonb_build_object('code', 'not_found', 'message', 'Contract not found.'));
  end if;
  select * into e from public.events where tenant_id = c.tenant_id and id = c.event_id;
  select * into p from public.proposals where tenant_id = c.tenant_id and id = c.proposal_id;
  select * into t from public.tenants where id = c.tenant_id;
  v_frozen := c.party_snapshot -> 'business';

  if t.archived_at is not null then
    v_problems := v_problems || jsonb_build_object('code', 'tenant_archived', 'message', 'This business is archived.');
  end if;
  if e.archived_at is not null then
    v_problems := v_problems || jsonb_build_object('code', 'event_archived',
      'message', 'The event is archived. Unarchive it before sending.');
  end if;
  -- Draft (to send) and sent (to resend) contracts may proceed.
  if c.status not in ('draft', 'sent') then
    v_problems := v_problems || jsonb_build_object('code', 'not_current_draft',
      'message', 'This contract is ' || c.status || ' and can no longer be sent. Open the current contract.');
  end if;
  if p.status <> 'approved' or e.active_proposal_id is distinct from c.proposal_id then
    v_problems := v_problems || jsonb_build_object('code', 'approval_superseded',
      'message', 'The approval this contract was built from is no longer current. Generate a contract from the current approval.');
  end if;

  select cl.id, cl.name, cl.email, cl.archived_at into v_signer
  from public.event_clients ec join public.clients cl on cl.tenant_id = ec.tenant_id and cl.id = ec.client_id
  where ec.tenant_id = c.tenant_id and ec.event_id = c.event_id and ec.can_sign;
  if not found then
    v_problems := v_problems || jsonb_build_object('code', 'signer_missing',
      'message', 'The event has no contact marked as signer.');
  elsif v_signer.id <> c.signer_client_id or v_signer.name <> c.signer_name or v_signer.email <> c.signer_email
        or v_signer.archived_at is not null then
    v_problems := v_problems || jsonb_build_object('code', 'signer_changed',
      'message', 'The event''s signer is now ' || v_signer.name || ' (' || v_signer.email || '), but this contract names '
        || c.signer_name || ' (' || c.signer_email || '). Regenerate the contract.');
  end if;

  if t.business_address is null or t.contact_email is null then
    v_problems := v_problems || jsonb_build_object('code', 'business_settings_incomplete',
      'message', 'Business settings are incomplete. Set the legal name, address and contact email in Business settings.');
  end if;
  if nullif(btrim(v_frozen ->> 'legal_name'), '') is null or nullif(btrim(v_frozen ->> 'address'), '') is null
     or nullif(btrim(v_frozen ->> 'contact_email'), '') is null then
    v_problems := v_problems || jsonb_build_object('code', 'business_identity_missing',
      'message', 'This contract was generated without a complete business identity. Regenerate it after completing Business settings.');
  else
    if v_frozen ->> 'legal_name' is distinct from t.business_name then v_identity_changes := array_append(v_identity_changes, 'legal name'); end if;
    if v_frozen ->> 'address' is distinct from t.business_address then v_identity_changes := array_append(v_identity_changes, 'address'); end if;
    if v_frozen ->> 'contact_email' is distinct from t.contact_email then v_identity_changes := array_append(v_identity_changes, 'contact email'); end if;
    if cardinality(v_identity_changes) > 0 then
      v_problems := v_problems || jsonb_build_object('code', 'business_changed',
        'message', 'Business settings changed since this contract was generated (' || array_to_string(v_identity_changes, ', ')
          || '). Regenerate the contract to use the current details.');
    end if;
  end if;
  if c.deposit_percent <> t.deposit_percent then
    v_problems := v_problems || jsonb_build_object('code', 'deposit_changed',
      'message', 'The deposit setting is now ' || t.deposit_percent || '%, but this contract uses ' || c.deposit_percent
        || '%. Regenerate the contract to use the current setting.');
  end if;
  return v_problems;
end;
$$;

create or replace function private.contracts_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status <> 'draft' then
    raise exception 'contracts are created as drafts' using errcode = 'check_violation';
  end if;
  if exists (select 1 from public.events e where e.tenant_id = new.tenant_id and e.id = new.event_id and e.archived_at is not null) then
    raise exception 'contract_not_allowed: the event is archived' using errcode = 'invalid_parameter_value';
  end if;
  -- After sending, a replacement needs the sent contract voided first.
  if exists (select 1 from public.contracts k where k.tenant_id = new.tenant_id and k.event_id = new.event_id and k.status in ('sent', 'signed')) then
    raise exception 'contract_not_allowed: a contract has already been sent for this event. Void it before generating a replacement'
      using errcode = 'invalid_parameter_value';
  end if;
  if not exists (
    select 1 from public.contract_template_versions v
    where v.tenant_id = new.tenant_id and v.id = new.template_version_id
      and v.published_at is not null and v.content_sha256 = new.template_content_sha256
  ) then
    raise exception 'contracts can only be generated from a published template version' using errcode = 'check_violation';
  end if;
  if not exists (
    select 1 from public.proposals p
    join public.events e on e.tenant_id = p.tenant_id and e.id = p.event_id
    where p.tenant_id = new.tenant_id and p.id = new.proposal_id
      and p.status = 'approved' and e.active_proposal_id = p.id
  ) then
    raise exception 'contracts can only be generated from the event''s current approved proposal' using errcode = 'check_violation';
  end if;
  new.status_changed_at := null;
  new.content_sha256 := private.contract_content_sha256(
    new.rendered_content, new.commercial_snapshot, new.party_snapshot, new.template_version_id, new.template_content_sha256);
  return new;
end;
$$;

create or replace function private.set_event_archived(p_event_id uuid, p_archived boolean, p_actor_type text, p_actor_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event public.events%rowtype;
  v_proposals uuid[];
  v_links int := 0;
  v_sessions int := 0;
  v_emails int := 0;
  v_contract_emails int := 0;
begin
  select * into v_event from public.events where id = p_event_id for update;
  if not found then
    raise exception 'not found' using errcode = 'no_data_found';
  end if;
  if p_archived = (v_event.archived_at is not null) then
    return jsonb_build_object('status', case when p_archived then 'archived' else 'active' end, 'replayed', true);
  end if;

  if p_archived then
    select coalesce(array_agg(p.id), '{}') into v_proposals
    from public.proposals p where p.tenant_id = v_event.tenant_id and p.event_id = v_event.id;
    -- Lock order everywhere: event, then proposals.
    perform 1 from public.proposals p where p.id = any (v_proposals) for update;

    update public.events set archived_at = now() where id = v_event.id;
    update public.access_links set revoked_at = now()
      where tenant_id = v_event.tenant_id and proposal_id = any (v_proposals) and revoked_at is null;
    get diagnostics v_links = row_count;
    update public.proposal_sessions set revoked_at = now()
      where tenant_id = v_event.tenant_id and proposal_id = any (v_proposals) and revoked_at is null;
    get diagnostics v_sessions = row_count;
    update public.email_outbox set status = 'cancelled', last_error = 'event archived'
      where tenant_id = v_event.tenant_id and entity_id = any (v_proposals)
        and event_type in ('proposal_sent', 'proposal_approved') and status = 'pending';
    get diagnostics v_emails = row_count;
    -- Contract invitations share the proposal links table and were revoked
    -- above; their pending emails are cancelled here.
    update public.email_outbox set status = 'cancelled', last_error = 'event archived'
      where tenant_id = v_event.tenant_id and entity_type = 'contract' and status = 'pending'
        and entity_id in (select k.id from public.contracts k where k.tenant_id = v_event.tenant_id and k.event_id = v_event.id);
    get diagnostics v_contract_emails = row_count;
    v_emails := v_emails + v_contract_emails;
  else
    update public.events set archived_at = null where id = v_event.id;
  end if;

  perform private.audit(v_event.tenant_id, 'event', v_event.id, case when p_archived then 'archived' else 'unarchived' end,
    p_actor_type, p_actor_id,
    case when p_archived then jsonb_build_object('links_revoked', v_links, 'sessions_revoked', v_sessions, 'emails_cancelled', v_emails)
         else '{}'::jsonb end);
  return jsonb_build_object('status', case when p_archived then 'archived' else 'active' end, 'replayed', false,
                            'links_revoked', v_links, 'sessions_revoked', v_sessions, 'emails_cancelled', v_emails);
end;
$$;


-- A revised offer that supersedes the approved proposal also supersedes its
-- draft contracts and voids its sent contracts, revoking their invitations.
create or replace function private.proposals_supersede_contract_drafts()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  k record;
begin
  update public.contracts set status = 'superseded'
    where tenant_id = new.tenant_id and proposal_id = new.id and status = 'draft';
  for k in select id from public.contracts where tenant_id = new.tenant_id and proposal_id = new.id and status = 'sent' loop
    update public.contracts set status = 'void', void_reason = 'A revised offer replaced the approved terms.' where id = k.id;
    perform private.retire_contract_invitations(k.id, 'superseded by a revised offer');
    perform private.audit(new.tenant_id, 'contract', k.id, 'voided', 'system', null, jsonb_build_object('reason', 'superseded by a revised offer'));
  end loop;
  return null;
end;
$$;

-- ===========================================================================
-- Staff: send, resend, void
-- ===========================================================================

create function private.masked_email(p_email text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select left(split_part(p_email, '@', 1), 1) || '•••@' || split_part(p_email, '@', 2);
$$;
grant execute on function private.masked_email(text) to authenticated, service_role;

-- Locks event, proposal, contract (in that order) after authorizing staff.
create function private.lock_contract_for_staff(p_contract_id uuid)
returns public.contracts
language plpgsql
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
begin
  select * into c from public.contracts where id = p_contract_id;
  if not found then
    raise exception 'not found' using errcode = 'no_data_found';
  end if;
  perform private.require_staff_of(c.tenant_id);
  perform 1 from public.events where tenant_id = c.tenant_id and id = c.event_id for update;
  perform 1 from public.proposals where tenant_id = c.tenant_id and id = c.proposal_id for update;
  select * into c from public.contracts where id = p_contract_id for update;
  return c;
end;
$$;
revoke execute on function private.lock_contract_for_staff(uuid) from public, anon, authenticated;

create function private.contract_problem_text(p_problems jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select string_agg(p ->> 'message', ' ') from jsonb_array_elements(p_problems) p;
$$;

create function private.issue_contract_invitation(c public.contracts, p_link_id uuid, p_token_hash text)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expires timestamptz := now() + interval '14 days';
begin
  if p_link_id is null or p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid access link' using errcode = 'invalid_parameter_value';
  end if;
  insert into public.access_links (id, tenant_id, purpose, proposal_id, contract_id, intended_client_id, token_hash, expires_at)
  values (p_link_id, c.tenant_id, 'contract', c.proposal_id, c.id, c.signer_client_id, p_token_hash, v_expires);
  perform private.enqueue_contract_email(
    c.tenant_id, 'contract_sent', c.signer_email, c.id, p_link_id,
    jsonb_build_object(
      'client_name', c.signer_name,
      'event_title', c.party_snapshot -> 'event' ->> 'title',
      'legal_name', coalesce(c.party_snapshot -> 'business' ->> 'legal_name', c.party_snapshot -> 'business' ->> 'name'),
      'contact_email', c.party_snapshot -> 'business' ->> 'contact_email',
      'deposit_cents', c.deposit_cents, 'deposit_percent', c.deposit_percent, 'currency', c.currency,
      'invitation_expires_at', v_expires),
    'contract_sent:' || p_link_id);
  return v_expires;
end;
$$;
revoke execute on function private.issue_contract_invitation(public.contracts, uuid, text) from public, anon, authenticated;

-- Sends the current eligible draft. Repeats (including concurrent ones, which
-- wait on the event lock) return the existing result without new links or
-- emails. The event stays awaiting_signature; nothing is booked.
create function public.send_contract(p_contract_id uuid, p_link_id uuid, p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
  v_problems jsonb;
  v_expires timestamptz;
begin
  c := private.lock_contract_for_staff(p_contract_id);
  if c.status = 'sent' then
    return jsonb_build_object('status', 'sent', 'replayed', true, 'contract_id', c.id, 'sent_at', c.sent_at,
      'recipient_email', c.signer_email);
  end if;
  v_problems := private.contract_send_problems(c.id);
  if c.status <> 'draft' then
    raise exception 'contract_not_sendable: this contract is %', c.status using errcode = 'invalid_parameter_value';
  end if;
  if jsonb_array_length(v_problems) > 0 then
    raise exception 'contract_not_sendable: %', private.contract_problem_text(v_problems) using errcode = 'invalid_parameter_value';
  end if;

  perform set_config('flux.sending_contract', c.id::text, true);
  update public.contracts set status = 'sent' where id = c.id returning * into c;
  perform set_config('flux.sending_contract', '', true);
  v_expires := private.issue_contract_invitation(c, p_link_id, p_token_hash);
  perform private.audit(c.tenant_id, 'contract', c.id, 'sent', 'staff', (select auth.uid()),
    jsonb_build_object('invitation_id', p_link_id, 'content_sha256', c.content_sha256));
  return jsonb_build_object('status', 'sent', 'replayed', false, 'contract_id', c.id, 'sent_at', c.sent_at,
    'recipient_email', c.signer_email, 'invitation_expires_at', v_expires);
end;
$$;

-- Resends an unchanged sent contract with a fresh invitation. Earlier
-- invitations are revoked and their pending emails cancelled; sent_at,
-- content, hashes and any event access already granted are untouched.
-- Rate limited: one resend per 2 minutes and 10 per day per contract.
create function public.resend_contract(p_contract_id uuid, p_link_id uuid, p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
  v_problems jsonb;
  v_expires timestamptz;
begin
  c := private.lock_contract_for_staff(p_contract_id);
  if c.status <> 'sent' then
    raise exception 'contract_not_resendable: only a sent, unsigned contract can be resent (this one is %)', c.status
      using errcode = 'invalid_parameter_value';
  end if;
  v_problems := private.contract_send_problems(c.id);
  if jsonb_array_length(v_problems) > 0 then
    raise exception 'contract_not_sendable: %', private.contract_problem_text(v_problems) using errcode = 'invalid_parameter_value';
  end if;
  if exists (select 1 from public.access_links l where l.purpose = 'contract' and l.contract_id = c.id
             and l.created_at > now() - interval '2 minutes')
     or (select count(*) from public.access_links l where l.purpose = 'contract' and l.contract_id = c.id
         and l.created_at > now() - interval '1 day') >= 10 then
    raise exception 'contract_resend_too_soon: this contract was sent very recently. Wait a few minutes before resending'
      using errcode = 'invalid_parameter_value';
  end if;

  perform private.retire_contract_invitations(c.id, 'replaced by a resend');
  v_expires := private.issue_contract_invitation(c, p_link_id, p_token_hash);
  perform private.audit(c.tenant_id, 'contract', c.id, 'resent', 'staff', (select auth.uid()), jsonb_build_object('invitation_id', p_link_id));
  return jsonb_build_object('status', 'sent', 'contract_id', c.id, 'sent_at', c.sent_at, 'recipient_email', c.signer_email,
    'invitation_expires_at', v_expires);
end;
$$;

-- Voids an unsigned sent contract. Content and history are kept; invitations
-- are revoked and pending contract emails cancelled; clients can no longer
-- read it. Event access, other events and Auth identities are untouched. A
-- replacement draft can then be generated from the current approval.
create function public.void_contract(p_contract_id uuid, p_reason text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
begin
  if p_reason is null or length(btrim(p_reason)) not between 1 and 500 then
    raise exception 'contract_void_invalid: give a reason (up to 500 characters)' using errcode = 'invalid_parameter_value';
  end if;
  c := private.lock_contract_for_staff(p_contract_id);
  if c.status = 'void' then
    return jsonb_build_object('status', 'void', 'replayed', true);
  end if;
  if c.status <> 'sent' then
    raise exception 'contract_void_invalid: only a sent, unsigned contract can be voided (this one is %)', c.status
      using errcode = 'invalid_parameter_value';
  end if;
  update public.contracts set status = 'void', void_reason = btrim(p_reason) where id = c.id;
  perform private.retire_contract_invitations(c.id, 'contract voided');
  perform private.audit(c.tenant_id, 'contract', c.id, 'voided', 'staff', (select auth.uid()), jsonb_build_object('reason', btrim(p_reason)));
  return jsonb_build_object('status', 'void', 'replayed', false);
end;
$$;

-- ===========================================================================
-- Client: request a verification email (service role, after rate limiting)
-- ===========================================================================

-- What an invitation (by id or token hash) currently allows. Shared checks.
create function private.contract_invitation(p_link_id uuid, p_token_hash text, p_tenant_slug text)
returns table (usable boolean, link_id uuid, tenant_id uuid, tenant_display_name text, contract_id uuid, event_id uuid,
               signer_client_id uuid, signer_email text, signer_name text, event_title text)
language sql
stable
security definer
set search_path = ''
as $$
  select (l.revoked_at is null and l.expires_at > now() and t.archived_at is null and c.status = 'sent'
          and e.archived_at is null and p.status = 'approved' and e.active_proposal_id = c.proposal_id),
         l.id, l.tenant_id, t.display_name, c.id, c.event_id, c.signer_client_id, c.signer_email, c.signer_name,
         c.party_snapshot -> 'event' ->> 'title'
  from public.access_links l
  join public.tenants t on t.id = l.tenant_id
  join public.contracts c on c.tenant_id = l.tenant_id and c.id = l.contract_id
  join public.events e on e.tenant_id = c.tenant_id and e.id = c.event_id
  join public.proposals p on p.tenant_id = c.tenant_id and p.id = c.proposal_id
  where l.purpose = 'contract' and t.slug = p_tenant_slug
    and ((p_link_id is not null and l.id = p_link_id) or (p_token_hash is not null and l.token_hash = p_token_hash));
$$;
revoke execute on function private.contract_invitation(uuid, text, text) from public, anon, authenticated;

-- Queues a verification email to the frozen signer address. The invitation
-- token only authorizes this; it never signs anyone in. At most 3 requests
-- per invitation per 15 minutes (the app also limits per IP).
create function public.request_contract_sign_in(p_token_hash text, p_tenant_slug text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  i record;
begin
  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('status', 'invalid');
  end if;
  select * into i from private.contract_invitation(null, p_token_hash, p_tenant_slug);
  if not found or not i.usable then
    return jsonb_build_object('status', 'invalid');
  end if;
  perform 1 from public.access_links where id = i.link_id for update;
  if (select count(*) from public.email_outbox o
      where o.access_link_id = i.link_id and o.event_type = 'contract_sign_in' and o.created_at > now() - interval '15 minutes') >= 3 then
    return jsonb_build_object('status', 'rate_limited');
  end if;
  perform private.enqueue_contract_email(i.tenant_id, 'contract_sign_in', i.signer_email, i.contract_id, i.link_id,
    jsonb_build_object('client_name', i.signer_name, 'event_title', i.event_title),
    'contract_sign_in:' || i.link_id || ':' || gen_random_uuid());
  perform private.audit(i.tenant_id, 'contract', i.contract_id, 'sign_in_requested', 'client', null, jsonb_build_object('invitation_id', i.link_id));
  return jsonb_build_object('status', 'ok', 'masked_email', private.masked_email(i.signer_email),
    'tenant_display_name', i.tenant_display_name);
end;
$$;

-- ===========================================================================
-- Client: verified acceptance and reading (authenticated)
-- ===========================================================================

-- The signed-in user's verified email, or null.
create function private.current_verified_email()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select lower(u.email) from auth.users u where u.id = (select auth.uid()) and u.email_confirmed_at is not null;
$$;
revoke execute on function private.current_verified_email() from public, anon, authenticated;

-- What the signed-in user may do with an invitation. Reveals the event and
-- signer only to the verified intended signer.
create function public.client_invitation_status(p_link_id uuid, p_tenant_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  i record;
  v_email text;
begin
  if (select auth.uid()) is null then
    return jsonb_build_object('state', 'signed_out');
  end if;
  select * into i from private.contract_invitation(p_link_id, null, p_tenant_slug);
  if not found or not i.usable then
    return jsonb_build_object('state', 'invalid');
  end if;
  v_email := private.current_verified_email();
  if v_email is null then
    return jsonb_build_object('state', 'unverified', 'tenant_display_name', i.tenant_display_name);
  end if;
  if v_email <> lower(i.signer_email) then
    return jsonb_build_object('state', 'wrong_account', 'tenant_display_name', i.tenant_display_name,
      'signed_in_email', v_email, 'intended_email', private.masked_email(i.signer_email));
  end if;
  return jsonb_build_object(
    'state', case when exists (
      select 1 from public.event_access ea where ea.tenant_id = i.tenant_id and ea.event_id = i.event_id
        and ea.user_id = (select auth.uid()) and ea.client_id = i.signer_client_id and ea.revoked_at is null)
      then 'accepted' else 'ready' end,
    'tenant_display_name', i.tenant_display_name, 'event_title', i.event_title, 'signer_name', i.signer_name,
    'contract_id', i.contract_id);
end;
$$;

-- Grants the verified signer access to the event, idempotently, after
-- rechecking everything under the event lock. Never grants planning or books.
create function public.accept_contract_invitation(p_link_id uuid, p_tenant_slug text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  i record;
  v_uid uuid := (select auth.uid());
  v_email text;
  v_existing record;
begin
  if v_uid is null then
    return jsonb_build_object('state', 'signed_out');
  end if;
  select * into i from private.contract_invitation(p_link_id, null, p_tenant_slug);
  if not found then
    return jsonb_build_object('state', 'invalid');
  end if;
  perform 1 from public.events where tenant_id = i.tenant_id and id = i.event_id for update;
  select * into i from private.contract_invitation(p_link_id, null, p_tenant_slug);
  if not i.usable then
    return jsonb_build_object('state', 'invalid');
  end if;
  v_email := private.current_verified_email();
  if v_email is null then
    return jsonb_build_object('state', 'unverified');
  end if;
  if v_email <> lower(i.signer_email) then
    return jsonb_build_object('state', 'wrong_account');
  end if;
  if not exists (select 1 from public.event_clients ec where ec.tenant_id = i.tenant_id and ec.event_id = i.event_id
                 and ec.client_id = i.signer_client_id) then
    return jsonb_build_object('state', 'invalid');
  end if;

  select ea.client_id into v_existing from public.event_access ea
  where ea.tenant_id = i.tenant_id and ea.event_id = i.event_id and ea.user_id = v_uid and ea.revoked_at is null;
  if found and v_existing.client_id <> i.signer_client_id then
    return jsonb_build_object('state', 'invalid');
  end if;
  if not found then
    insert into public.event_access (tenant_id, event_id, client_id, user_id)
    values (i.tenant_id, i.event_id, i.signer_client_id, v_uid);
    perform private.audit(i.tenant_id, 'event', i.event_id, 'client_access_granted', 'client', v_uid,
      jsonb_build_object('contract_id', i.contract_id, 'invitation_id', i.link_id));
  end if;
  update public.access_links set consumed_at = now() where id = i.link_id and consumed_at is null;
  return jsonb_build_object('state', 'accepted', 'contract_id', i.contract_id);
end;
$$;

-- Whether the signed-in user may read this contract right now.
create function private.client_can_read_contract(p_contract_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.contracts c
    join public.events e on e.tenant_id = c.tenant_id and e.id = c.event_id
    join public.tenants t on t.id = c.tenant_id
    join public.proposals p on p.tenant_id = c.tenant_id and p.id = c.proposal_id
    join public.event_access ea on ea.tenant_id = c.tenant_id and ea.event_id = c.event_id
      and ea.user_id = (select auth.uid()) and ea.client_id = c.signer_client_id and ea.revoked_at is null
    where c.id = p_contract_id and c.status = 'sent' and e.archived_at is null and t.archived_at is null
      and p.status = 'approved' and e.active_proposal_id = c.proposal_id
      and lower(c.signer_email) = private.current_verified_email()
  );
$$;
revoke execute on function private.client_can_read_contract(uuid) from public, anon, authenticated;

-- The client's read-only view of a sent contract: an explicit safe DTO of
-- frozen data only. Anything not readable returns {"state":"unavailable"}.
create function public.client_contract_view(p_contract_id uuid, p_tenant_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
  t public.tenants%rowtype;
begin
  select k.* into c from public.contracts k join public.tenants tt on tt.id = k.tenant_id
  where k.id = p_contract_id and tt.slug = p_tenant_slug;
  if not found or not private.client_can_read_contract(c.id) then
    return jsonb_build_object('state', 'unavailable');
  end if;
  select * into t from public.tenants where id = c.tenant_id;
  return jsonb_build_object(
    'state', 'available',
    'brand', jsonb_build_object('display_name', t.display_name, 'brand_colors', t.brand_colors),
    'contract', jsonb_build_object(
      'id', c.id, 'sent_at', c.sent_at, 'content_sha256', c.content_sha256, 'rendered_content', c.rendered_content,
      'signer_name', c.signer_name, 'currency', c.currency, 'total_cents', c.total_cents,
      'deposit_percent', c.deposit_percent, 'deposit_cents', c.deposit_cents, 'balance_cents', c.balance_cents,
      'balance_due_date', c.balance_due_date,
      'event_title', c.party_snapshot -> 'event' ->> 'title', 'event_date', c.party_snapshot -> 'event' ->> 'date',
      'legal_name', coalesce(c.party_snapshot -> 'business' ->> 'legal_name', c.party_snapshot -> 'business' ->> 'name'))
  );
end;
$$;

-- Contracts the signed-in client can read (client home).
create function public.my_contracts()
returns table (tenant_slug text, tenant_display_name text, contract_id uuid, event_title text, event_date text, sent_at timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
  select t.slug, t.display_name, c.id, c.party_snapshot -> 'event' ->> 'title', c.party_snapshot -> 'event' ->> 'date', c.sent_at
  from public.contracts c
  join public.tenants t on t.id = c.tenant_id
  join public.event_access ea on ea.tenant_id = c.tenant_id and ea.event_id = c.event_id
    and ea.user_id = (select auth.uid()) and ea.revoked_at is null
  where c.status = 'sent' and private.client_can_read_contract(c.id)
  order by c.sent_at desc;
$$;

-- ===========================================================================
-- Grants
-- ===========================================================================

revoke execute on function
  public.send_contract(uuid, uuid, text),
  public.resend_contract(uuid, uuid, text),
  public.void_contract(uuid, text),
  public.request_contract_sign_in(text, text),
  public.client_invitation_status(uuid, text),
  public.accept_contract_invitation(uuid, text),
  public.client_contract_view(uuid, text),
  public.my_contracts()
  from public, anon;
revoke execute on function public.request_contract_sign_in(text, text) from authenticated;
grant execute on function
  public.send_contract(uuid, uuid, text),
  public.resend_contract(uuid, uuid, text),
  public.void_contract(uuid, text),
  public.client_invitation_status(uuid, text),
  public.accept_contract_invitation(uuid, text),
  public.client_contract_view(uuid, text),
  public.my_contracts()
  to authenticated;
grant execute on function public.request_contract_sign_in(text, text) to service_role;
grant execute on function private.contract_problem_text(jsonb) to authenticated, service_role;

-- ===========================================================================
-- Staff review now reflects real sending
-- ===========================================================================

create or replace function public.review_contract_for_send(p_contract_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  c public.contracts%rowtype;
  v_problems jsonb;
begin
  select * into c from public.contracts where id = p_contract_id;
  if not found then
    raise exception 'not found' using errcode = 'no_data_found';
  end if;
  perform private.require_staff_of(c.tenant_id);
  v_problems := private.contract_send_problems(c.id);
  return jsonb_build_object(
    'contract_id', c.id,
    'status', c.status,
    'sent_at', c.sent_at,
    'eligible', jsonb_array_length(v_problems) = 0,
    'problems', v_problems,
    'can_send', c.status = 'draft' and jsonb_array_length(v_problems) = 0,
    'send_unavailable_reason', case
      when c.status = 'sent' then 'This contract has already been sent. Resend or void it from the contract page.'
      when c.status <> 'draft' then 'This contract is ' || c.status || ' and cannot be sent.'
      when jsonb_array_length(v_problems) > 0 then 'Fix the problems above before sending.'
      end,
    'signer', jsonb_build_object('name', c.signer_name, 'email', c.signer_email),
    'business', c.party_snapshot -> 'business',
    'deposit_percent', c.deposit_percent,
    'deposit_cents', c.deposit_cents,
    'balance_cents', c.balance_cents,
    'total_cents', c.total_cents,
    'currency', c.currency,
    'balance_due_date', c.balance_due_date,
    'content_sha256', c.content_sha256
  );
end;
$$;
